val problemConditions = List(
	Condition(
		Trait.Nationality,
		Nationality.English,
		ConditionType.SameHouseAs,
		Trait.HouseColor,
		HouseColor.Red
	),
	Condition(
		Trait.Nationality,
		Nationality.Spanish,
		ConditionType.SameHouseAs,
		Trait.Pet,
		Pet.Dog
	),
	Condition(
		Trait.Drink,
		Drink.Coffee,
		ConditionType.SameHouseAs,
		Trait.HouseColor,
		Drink.Coffee
	),
)